# -*- coding: utf-8 -*-
"""
This family file was auto-generated by $Id: generate_family_file.py 9179 2011-04-15 10:59:23Z xqt $
Configuration parameters:
  url = https://www.noisebridge.net/
  name = noisebridge

Please do not commit this to the SVN repository!
"""

import family

class Family(family.Family):
    def __init__(self):
        family.Family.__init__(self)
        self.name = 'noisebridge'
        self.langs = {
            'en': u'www.noisebridge.net',
        }

        self.namespaces[4] = self.namespaces.get(4, {})
        self.namespaces[4]['en'] = [u'Noisebridge']
        self.namespaces[5] = self.namespaces.get(5, {})
        self.namespaces[5]['en'] = [u'Noisebridge talk']


    def scriptpath(self, code):
        return {
            'en': u'',
        }[code]

    def version(self, code):
        return {
            'en': u'1.15.3',
        }[code]
    
    def protocol(self, code):
        return 'https'
